#include "gcode.h"

Gcode::Gcode()
{

}

void Gcode::generate_file(Shape& shape)
{
    std::ofstream fout = create_empty_file();
    write_gcode(fout, shape);
    fout.close();
}

void Gcode::write_gcode(std::ofstream& fout, Shape& shape)
{
    write_initial_gcode(fout, shape);
    int numberOfLayers = shape.get_number_of_layers();
    for (int i{0}; i<numberOfLayers; i++)
    {
        int layerNumber{i};
        fout << "; Beginning layer: " << layerNumber << std::endl;
        write_layer_gcode(fout, shape, layerNumber);
    }

}

std::ofstream Gcode::create_empty_file()
{
    make_file_name_unique();
    std::string fileName = get_file_name();
    std::ofstream fout{fileName};
    if (fout.fail())
    {
        std::cout << "Failed to write to file." << std::endl;
    }
    return fout;
}

void Gcode::make_file_name_unique()
{
    std::string fileName = get_file_name();

    if (does_file_exist(fileName))
    {
        std::string suffix = "(1)";
        fileName = fileName + suffix;
    }

    set_file_name(fileName);
}

bool Gcode::does_file_exist(const std::string& fileName)
{
    struct stat buf;
    if (stat(fileName.c_str(), &buf) != -1)
    {
        return true;
    }
    return false;
}

std::string Gcode::get_file_name() const
{
    return mFileName;
}

void Gcode::set_file_name(std::string const fileName)
{
    mFileName = fileName;
}

void Gcode::write_layer_gcode(std::ofstream& fout, Shape& shape, int layerNumber)
{
    Layer* layer = shape.get_layer(layerNumber);

    double zLocation = layer->get_location();
    fout << "G1 " << "Z" << zLocation;
    fout << " F1200.000" << std::endl;

    write_points_in_layer(fout,layer);
}

void Gcode::write_points_in_layer(std::ofstream& fout, Layer* layer)
{
    std::vector<Point> pointsInLayer = layer->get_points();
    size_t numberOfPointsInLayer = pointsInLayer.size();
    for (int i{0}; i<numberOfPointsInLayer; i++)
    {
        Point point = pointsInLayer[i];
        fout << "G1 ";
        fout << " X" << point.get_x();
        fout << " Y" << point.get_y();
//        fout << " A" << point.get_a();
        fout << " M" << point.get_material();
        fout << std::endl;
    }
}

void Gcode::write_initial_gcode(std::ofstream& fout, Shape& shape)
{
//    fout << "File created: " << std::endl;
    fout << "Gcode generated by FRE_Slicer." << std::endl;
    fout << std::endl;

    fout << "G28 ; home all axes" << std::endl;
    fout << "G21 ; set units to millimeters" << std::endl;
    fout << "G90 ; use absolute coordinates" << std::endl;
    fout << std::endl;
}
